services:
  postgres:
    image: postgres:latest
    container_name: postgre
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: channels_data
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
