services:
  postgres:
    image: postgres:17.2
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: channels_data
    ports:
      - "5432:5432"
    volumes:
      - /root/postgres_data:/var/lib/postgresql/data

      - /root/YouTubeContentManagement-DataEng/sql/:/docker-entrypoint-initdb.d # subject to chanage based on repo location on host

      - /root/raw-channel-data/:/docker-entrypoint-initdb.d/raw-channel-data

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

volumes:
  postgres_data:
